---
title: "Homework4"
author: "aslepchenkov"
date: "May 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(randomForest)
library(rpart)
library(rattle)
library(tidyr)
library(rpart.plot)
library(RColorBrewer)
```

```{r}
ages <- read.table("ages.tsv", sep="\t", header=1)
head(ages)
methylation <- read.table("methylation.tsv", sep="\t", header=1, row.names = 1, na.strings = "NA")
print(methylation[1:5, 1:5])
methylation[is.na(methylation)] = 0  # Change NA to 0

Переподготовка:

Для каждого сайта метилирования, посчитать корреляцию между долей метилирования этого сайта в доноре и возрасте донора.
Оставить только 10 самых скоррелированных сайтов. Под самыми скоррелированными мы понимаем абсолютное значение корреляции.



cor_data <- apply(methylation, MARGIN = 1, FUN = function(x) return(cor.test(as.numeric(x[-1:-3]), ages$Age, method = "pearson")$estimate))
best_cor <- tail(sort(abs(cor_data)), n = 10)
# plot(ages$Age, as.numeric(data[-1:-3]))
# plot(ages$Age, methylation[64, -1:-3])
data <- methylation[rownames(methylation) %in% names(best_cor), -1:-3]
data <- t(data)
# data <- gather(cbind(data, site = rownames(data)), key = site, value = meth_level)
# colnames(data)[2] <- "patient"

data <- cbind(data, age = ages["Age"])
head(data)
```

```{r ML}
set.seed(123896527)

validation <- sample(nrow(data), 10)
# training <- ages$Sample[!(ages$Sample %in% validation)]

training_data <- data[-validation, ]
validation_data <- data[validation,]

rmse <- function(real, predicted) {
  sqrt(sum((real - predicted) ^ 2) / length(real))
}


#' randomForest wrapper and error estimator
#'
#' @param train.data data.frame, training dataset
#' @param train.response numeric vector, values of dependent variables in training dataset
#' @param test.data data.frame, testing (validation) dataset
#' @param test.response numeric vector, values of dependent variables in testing dataset
#' @param runs.number numeric (integer), how many times we should run random forest
#' @param ... parameters that are passes to randomForest function, like
#'        ntree, mtry, nodesize, replace, sampsize
#'
#' @return numeric vector with two values, 
#'      first is mean of RMSE values on training data
#'      second is mean of RMSE values on testing data
#' @export
#'
#' @examples
wrapper <- function(training_data, training_response,
                    validation_data, validation_response, 
                    runs_number=50, ...) {
  
  training_rmse = vector()
  validation_rmse = vector()
  for(i in 1:runs_number) {
    
    forest <- randomForest(Age ~ .,
                       data = training_data,
                       ...)
    prediction_training <- predict(forest, training_data)
    training_rmse[i] = rmse(training_response, prediction_training)

    prediction_validation <- predict(forest, validation_data)
    validation_rmse[i] = rmse(validation_response, prediction_validation)    
  }
  
  return(c(mean(training_rmse), mean(validation_rmse)))
  
}

wrapper(training_data, training_data$Age, validation_data, validation_data$Age, 50, nodesize=1, replace=F, sampsize=20, mtry=5, ntree=100)

training_data

forest <- randomForest(age ~ site+meth_level,
                       data = training_data,
                       importance = T, ntree = 99,
                       replace = T,
                       keep.forest = T,
                       keep.inbag = T,
                       nodesize=1,
                       sampsize=300
                       )

```

